version: '3.3'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
      
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres
    environment:
      - POSTGRES_DB=greatness
      - POSTGRES_USER=axelor
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres-data:


# version: '3'

# services:
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - "8080:8080"
#     environment:
#       - POSTGRES_DB=greatness
#       - POSTGRES_USER=axelor
#       - POSTGRES_PASSWORD=password
#     image: axelor-open-suite

#   db:
#     image: postgres
#     environment:
#       - POSTGRES_DB=greatness
#       - POSTGRES_USER=axelor
#       - POSTGRES_PASSWORD=password
#     volumes:
#       - postgres-data:/var/lib/postgresql/data
#     ports:
#       - "5432:5432"

# volumes:
#   postgres-data: